### ISSUE TITLE
i need braincellz

### ISSUE THREAD

**Issue by bqbbo** [lumauser/lumauser.github.io#1]
there is an issue

im running out of braincellz
why are u coding at 10 pm jiho

go to bed

`print("Goodbye, World!")`

**Comment by bqbbo** [comment]
the actual issue is ur navbar on rulez is not in a ol tag

wait is that what I did for my site

I gotta check

**Comment by lumauser** [comment]
Hi Bobby

**Comment by lumauser** [comment]
Ikr my nav bar is broken lol

**Comment by bqbbo** [comment]
u seem to have it covered
