### ISSUE TITLE
Pages/.. Navbar & Formatting QOL

### ISSUE THREAD

**Issue by bqbbo** [lumauser/lumauser.github.io#3]
Unnecessary double ID initialization on Rulez.html and Beatbox Edition.html

Formatting issues with Rulez.html

**Comment by lumauser** [comment]
So whenever I double tap on the rules and other pages it gives me the 404 page pls help

**Comment by bqbbo** [comment]
I looked at your code, index.html is fine, but you did ..Pages/[file].html instead of ../Pages/[file].html

I will create a pull request fixing the issues.

Edit: was playing geometry dash, sorry for the late response.

**Comment by bqbbo** [comment]
I have created the pull request, please go check that out and let me know when its accepted. Thanks!

**Comment by bqbbo** [comment]
Looks like you merged it, I was working on another feature you didn't have after you merged it, so could I create another request finishing it up?

**Comment by bqbbo** [comment]
Made a new pull request, please check that out. Thanks for accepting the changes!
