### ISSUE TITLE
CSS/JS linkage

### ISSUE THREAD

**Issue by bqbbo** [lumauser/lumauser.github.io#6]
CSS/JS linkage

If you'd like, I can do the CSS and add js files for the pages and index.
I don't know if you already saw the comment on the index, but i'd highly recommend checking to be sure its attributes are correct

**Comment by lumauser** [comment]
what do you mean I don't get it. I linked all the css and javascript files in the index.html file what do you mean I need to link my css and javascript files in the index.html

**Comment by bqbbo** [comment]
You have your index.html linked, but to style your navbar correctly you need to either have a repo wide css that every page can access, or you can make a new css file for every new html file you have, either works. However, if you want to use external css and add stuff other than the navbar etc. you will need to make an individual css files for the one you need

js is optional if you want some cool functionality

**Comment by bqbbo** [comment]
I have made a pull request with all of these features and more, I'd highly recommend you'd check it out, I spent more than 2 hours working and going back and fourth.
