### ISSUE TITLE
Bobby I need your help

### ISSUE THREAD

**Issue by lumauser** [lumauser/lumauser.github.io#8]
So I fixed some of the code after you made the pull request and some of it works but some of it don't work. So all the pages work its just that when I for example, go to a page to another page that is not the index.html, it just gives me the 404 error. Maybe is somewhere in the navbar that wrong idk. Don't do anything else because I'll try to make the other things by myself. Thanks!

**Comment by bqbbo** [comment]
Ok, I'll see what I can do.

**Comment by bqbbo** [comment]
It looks like you already fixed this issue. You can close this now.
